name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Type check
      run: bun run typecheck
    
    - name: Lint
      run: bun run lint
      continue-on-error: true
    
    - name: Format check
      run: bun run format
      continue-on-error: true
    
    - name: Build check
      run: bun run build